#!/usr/bin/env bash

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "请通过 source 加载 scripts/env/dev.sh。" >&2
  exit 1
fi

LEO_RUNTIME_ENV=dev

# shellcheck disable=SC1091
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

load_workspace_env

export LEO_RUNTIME_ENV=dev
export SPRING_PROFILES_ACTIVE=dev
export SPRING_DATASOURCE_DB="${LEO_DEV_DATASOURCE_DB:-leo}"

set_backend_common_defaults

export LEO_AUTH_REFRESH_COOKIE_SECURE="${LEO_AUTH_REFRESH_COOKIE_SECURE:-false}"
export LEO_AUTH_REFRESH_COOKIE_SAME_SITE="${LEO_AUTH_REFRESH_COOKIE_SAME_SITE:-Lax}"
export LEO_CORS_ALLOWED_ORIGINS="${LEO_CORS_ALLOWED_ORIGINS:-http://localhost:3100,http://127.0.0.1:3100}"
export LEO_CORS_ALLOW_CREDENTIALS="${LEO_CORS_ALLOW_CREDENTIALS:-true}"
export LEO_CORS_MAX_AGE_SECONDS="${LEO_CORS_MAX_AGE_SECONDS:-3600}"
export LEO_SECURITY_HSTS_ENABLED="${LEO_SECURITY_HSTS_ENABLED:-false}"
export SPRINGDOC_API_DOCS_ENABLED="${SPRINGDOC_API_DOCS_ENABLED:-true}"
export SPRINGDOC_SWAGGER_UI_ENABLED="${SPRINGDOC_SWAGGER_UI_ENABLED:-true}"
export LEO_DOCS_PUBLIC_ACCESS_ENABLED="${LEO_DOCS_PUBLIC_ACCESS_ENABLED:-false}"
export LEO_HEALTH_PAGE_ENABLED="${LEO_HEALTH_PAGE_ENABLED:-true}"
export LEO_HEALTH_PAGE_PUBLIC_ACCESS_ENABLED="${LEO_HEALTH_PAGE_PUBLIC_ACCESS_ENABLED:-true}"
