package com.leo.erp.purchase.inbound.web.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public record PurchaseInboundItemResponse(
        Long id,
        Integer lineNo,
        Long materialId,
        String materialCode,
        String brand,
        String category,
        String material,
        String spec,
        String length,
        String unit,
        Long sourcePurchaseOrderItemId,
        Long settlementCompanyId,
        String settlementCompanyName,
        Long warehouseId,
        String warehouseName,
        String settlementMode,
        String batchNo,
        String batchNoNormalized,
        Integer remainingQuantity,
        Integer quantity,
        String quantityUnit,
        BigDecimal pieceWeightTon,
        Integer piecesPerBundle,
        BigDecimal weightTon,
        BigDecimal weighWeightTon,
        BigDecimal weightAdjustmentTon,
        BigDecimal weightAdjustmentAmount,
        BigDecimal unitPrice,
        BigDecimal amount,
        String toleranceDirection,
        BigDecimal toleranceLimitPercent,
        BigDecimal toleranceActualPercent,
        String toleranceReasonCode,
        String toleranceRemark,
        Long toleranceConfirmedBy,
        String toleranceConfirmedName,
        LocalDateTime toleranceConfirmedAt
) {
    public PurchaseInboundItemResponse(Long id,
                                       Integer lineNo,
                                       String materialCode,
                                       String brand,
                                       String category,
                                       String material,
                                       String spec,
                                       String length,
                                       String unit,
                                       Long sourcePurchaseOrderItemId,
                                       Long settlementCompanyId,
                                       String settlementCompanyName,
                                       String warehouseName,
                                       String settlementMode,
                                       String batchNo,
                                       Integer remainingQuantity,
                                       Integer quantity,
                                       String quantityUnit,
                                       BigDecimal pieceWeightTon,
                                       Integer piecesPerBundle,
                                       BigDecimal weightTon,
                                       BigDecimal weighWeightTon,
                                       BigDecimal weightAdjustmentTon,
                                       BigDecimal weightAdjustmentAmount,
                                       BigDecimal unitPrice,
                                       BigDecimal amount) {
        this(id, lineNo, null, materialCode, brand, category, material, spec, length, unit,
                sourcePurchaseOrderItemId, settlementCompanyId, settlementCompanyName, null, warehouseName,
                settlementMode, batchNo, null, remainingQuantity, quantity, quantityUnit, pieceWeightTon,
                piecesPerBundle, weightTon, weighWeightTon, weightAdjustmentTon, weightAdjustmentAmount,
                unitPrice, amount, null, null, null, null, null, null, null, null);
    }

    public PurchaseInboundItemResponse(Long id,
                                       Integer lineNo,
                                       String materialCode,
                                       String brand,
                                       String category,
                                       String material,
                                       String spec,
                                       String length,
                                       String unit,
                                       Long sourcePurchaseOrderItemId,
                                       String warehouseName,
                                       String settlementMode,
                                       String batchNo,
                                       Integer remainingQuantity,
                                       Integer quantity,
                                       String quantityUnit,
                                       BigDecimal pieceWeightTon,
                                       Integer piecesPerBundle,
                                       BigDecimal weightTon,
                                       BigDecimal weighWeightTon,
                                       BigDecimal weightAdjustmentTon,
                                       BigDecimal weightAdjustmentAmount,
                                       BigDecimal unitPrice,
                                       BigDecimal amount) {
        this(id, lineNo, null, materialCode, brand, category, material, spec, length, unit,
                sourcePurchaseOrderItemId, null, null, null, warehouseName, settlementMode, batchNo, null,
                remainingQuantity, quantity, quantityUnit, pieceWeightTon, piecesPerBundle,
                weightTon, weighWeightTon, weightAdjustmentTon, weightAdjustmentAmount, unitPrice, amount,
                null, null, null, null, null, null, null, null);
    }
}
