#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_DIR="${LEO_RELEASE_DB_OUT_DIR:-$ROOT_DIR/release/db}"
OUT_SQL="${LEO_RELEASE_DB_OUT_SQL:-$OUT_DIR/postgresql-full-init.sql}"

DB_HOST="${LEO_RELEASE_DB_HOST:-${LEO_DB_ADMIN_HOST:-localhost}}"
DB_PORT="${LEO_RELEASE_DB_PORT:-${LEO_DB_ADMIN_PORT:-5432}}"
DB_ADMIN_USER="${LEO_RELEASE_DB_ADMIN_USER:-${LEO_DB_ADMIN_USER:-postgres}}"
DB_ADMIN_PASSWORD="${LEO_RELEASE_DB_ADMIN_PASSWORD:-${LEO_DB_ADMIN_PASSWORD:-${PGPASSWORD:-}}}"
PG_DUMP="${LEO_RELEASE_PG_DUMP:-pg_dump}"
TMP_DB="${LEO_RELEASE_TMP_DB:-leo_release_full_$(date +%Y%m%d%H%M%S)}"
WORK_DIR="${LEO_RELEASE_WORK_DIR:-$(mktemp -d /tmp/leo-release-schema-src.XXXXXX)}"
DB_STATEMENT_TIMEOUT="${LEO_RELEASE_DB_STATEMENT_TIMEOUT:-${LEO_POSTGRES_STATEMENT_TIMEOUT:-60s}}"
DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT="${LEO_RELEASE_DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT:-${LEO_POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT:-120s}}"
DB_LOCK_TIMEOUT="${LEO_RELEASE_DB_LOCK_TIMEOUT:-${LEO_POSTGRES_LOCK_TIMEOUT:-10s}}"

export PGPASSWORD="$DB_ADMIN_PASSWORD"

cleanup() {
  dropdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER" --if-exists "$TMP_DB" >/dev/null 2>&1 || true
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

mkdir -p "$OUT_DIR"
git -C "$ROOT_DIR" archive HEAD | tar -x -C "$WORK_DIR"

sql_literal() {
  printf '%s' "$1" | sed "s/'/''/g"
}

DB_STATEMENT_TIMEOUT_SQL="$(sql_literal "$DB_STATEMENT_TIMEOUT")"
DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT_SQL="$(sql_literal "$DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT")"
DB_LOCK_TIMEOUT_SQL="$(sql_literal "$DB_LOCK_TIMEOUT")"

createdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER" -E UTF8 "$TMP_DB"
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER" -d "$TMP_DB" \
  -v ON_ERROR_STOP=1 -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' >/dev/null

cd "$WORK_DIR"
mvn -q org.flywaydb:flyway-maven-plugin:11.20.3:migrate \
  -Dflyway.url="jdbc:postgresql://$DB_HOST:$DB_PORT/$TMP_DB" \
  -Dflyway.user="$DB_ADMIN_USER" \
  -Dflyway.password="$DB_ADMIN_PASSWORD" \
  -Dflyway.locations=filesystem:src/main/resources/db/migration \
  -Dflyway.schemas=public \
  -Dflyway.defaultSchema=public \
  -Dflyway.baselineOnMigrate=false \
  -Dflyway.cleanDisabled=true \
  -Dflyway.placeholderReplacement=false \
  -Dflyway.validateOnMigrate=true

"$PG_DUMP" -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER" -d "$TMP_DB" \
  --schema=public \
  --no-owner \
  --no-privileges \
  --if-exists \
  --clean \
  --encoding=UTF8 \
  --file="$OUT_SQL.tmp"

{
  printf -- '-- Leo ERP PostgreSQL offline full initialization script\n'
  printf -- '-- Generated from git commit: %s\n' "$(git -C "$ROOT_DIR" rev-parse --short HEAD)"
  printf -- '-- Generated at: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf -- '-- Generated by applying Flyway migrations V1..latest to a clean temporary PostgreSQL database.\n'
  printf -- '-- Includes schema, seed/system data, and flyway_schema_history.\n'
  printf -- '-- PostgreSQL target: 16+\n'
  printf -- '-- Usage: psql -v ON_ERROR_STOP=1 -d <database> -f postgresql-full-init.sql\n\n'
  printf -- "SET client_encoding = 'UTF8';\n"
  printf -- 'SET standard_conforming_strings = on;\n\n'
  printf -- '-- Runtime database defaults for application sessions.\n'
  printf -- 'DO $leo_db_runtime_defaults$\n'
  printf -- 'BEGIN\n'
  printf -- "  EXECUTE format('ALTER DATABASE %%I SET statement_timeout = %%L', current_database(), '%s');\n" "$DB_STATEMENT_TIMEOUT_SQL"
  printf -- "  EXECUTE format('ALTER DATABASE %%I SET idle_in_transaction_session_timeout = %%L', current_database(), '%s');\n" "$DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT_SQL"
  printf -- "  EXECUTE format('ALTER DATABASE %%I SET lock_timeout = %%L', current_database(), '%s');\n" "$DB_LOCK_TIMEOUT_SQL"
  printf -- "  EXECUTE format('ALTER ROLE %%I IN DATABASE %%I SET statement_timeout = %%L', current_user, current_database(), '%s');\n" "$DB_STATEMENT_TIMEOUT_SQL"
  printf -- "  EXECUTE format('ALTER ROLE %%I IN DATABASE %%I SET idle_in_transaction_session_timeout = %%L', current_user, current_database(), '%s');\n" "$DB_IDLE_IN_TRANSACTION_SESSION_TIMEOUT_SQL"
  printf -- "  EXECUTE format('ALTER ROLE %%I IN DATABASE %%I SET lock_timeout = %%L', current_user, current_database(), '%s');\n" "$DB_LOCK_TIMEOUT_SQL"
  printf -- 'END\n'
  printf -- '$leo_db_runtime_defaults$;\n\n'
  sed -E \
    -e '/^\\restrict /d' \
    -e '/^\\unrestrict /d' \
    -e '/^SET transaction_timeout = /d' \
    -e 's/^DROP SCHEMA IF EXISTS public;$/DROP SCHEMA IF EXISTS public CASCADE;/' \
    "$OUT_SQL.tmp"
} > "$OUT_SQL"

python3 - "$OUT_SQL" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
marker = "CREATE SCHEMA public;\n"
insert = "CREATE SCHEMA public;\n\nCREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;\n"
if "CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;" not in text:
    if marker not in text:
        raise SystemExit("CREATE SCHEMA public marker not found")
    text = text.replace(marker, insert, 1)
path.write_text(text)
PY

rm -f "$OUT_SQL.tmp"

psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_ADMIN_USER" -d "$TMP_DB" -v ON_ERROR_STOP=1 \
  -c "SELECT count(*) AS tables FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE';" \
  -c "SELECT version, description, success FROM flyway_schema_history ORDER BY installed_rank DESC LIMIT 5;"

printf 'Generated %s\n' "$OUT_SQL"
