package com.leo.erp.system.operationlog.support;

import com.leo.erp.security.permission.RequiresPermission;
import com.leo.erp.system.norule.service.SystemSwitchService;
import jakarta.servlet.http.HttpServletRequest;
import org.junit.jupiter.api.Test;
import org.springframework.web.method.HandlerMethod;
import org.springframework.web.servlet.HandlerMapping;

import java.lang.reflect.Method;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

class OperationLogMetadataResolverTest {

    private final SystemSwitchService systemSwitchService = mock(SystemSwitchService.class);
    private final OperationLogMetadataResolver resolver = new OperationLogMetadataResolver(systemSwitchService);

    @Test
    void shouldReturnNull_whenNoAnnotations() throws Exception {
        var handlerMethod = createHandlerMethod("noAnnotationMethod");
        var request = mock(HttpServletRequest.class);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldReturnMetadata_whenOperationLoggablePresent() throws Exception {
        var handlerMethod = createHandlerMethod("loggableMethod");
        var request = mock(HttpServletRequest.class);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNotNull();
        assertThat(result.moduleName()).isEqualTo("测试模块");
        assertThat(result.moduleNameField()).isEqualTo("moduleKey");
        assertThat(result.actionType()).isEqualTo("新增");
    }

    @Test
    void shouldReturnNull_whenAutoLogAndReadOnlyMethod() throws Exception {
        var handlerMethod = createHandlerMethod("requiresPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("GET");
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(false);
        when(systemSwitchService.shouldAutoRecordAllWriteOperations()).thenReturn(false);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldReturnAutoMetadataForWriteOperation_whenAutoRecordAllWriteEnabled() throws Exception {
        var handlerMethod = createHandlerMethod("requiresCreatePermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("POST");
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(false);
        when(systemSwitchService.shouldAutoRecordAllWriteOperations()).thenReturn(true);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNotNull();
        assertThat(result.moduleName()).isEqualTo("部门");
        assertThat(result.actionType()).isEqualTo("新增");
        assertThat(result.autoGenerated()).isTrue();
    }

    @Test
    void shouldReturnNullForWriteOperation_whenAutoRecordAllWriteDisabled() throws Exception {
        var handlerMethod = createHandlerMethod("requiresCreatePermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("POST");
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(false);
        when(systemSwitchService.shouldAutoRecordAllWriteOperations()).thenReturn(false);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldReturnDetailedQueryMetadata_whenDetailedPageActionEnabledWithoutPathId() throws Exception {
        var handlerMethod = createHandlerMethod("requiresPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("GET");
        when(request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE)).thenReturn(Map.of());
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(true);
        when(systemSwitchService.shouldRecordDetailedPageAction("QUERY")).thenReturn(true);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNotNull();
        assertThat(result.moduleName()).isEqualTo("test");
        assertThat(result.actionType()).isEqualTo("查询");
        assertThat(result.autoGenerated()).isTrue();
    }

    @Test
    void shouldReturnDetailedViewMetadata_whenDetailedPageActionEnabledWithPathId() throws Exception {
        var handlerMethod = createHandlerMethod("requiresDepartmentReadPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("GET");
        when(request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE)).thenReturn(Map.of("id", "100"));
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(true);
        when(systemSwitchService.shouldRecordDetailedPageAction("DETAIL")).thenReturn(true);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNotNull();
        assertThat(result.moduleName()).isEqualTo("部门");
        assertThat(result.actionType()).isEqualTo("查看");
        assertThat(result.autoGenerated()).isTrue();
    }

    @Test
    void shouldReturnNull_whenDetailedPageActionDisabled() throws Exception {
        var handlerMethod = createHandlerMethod("requiresPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("GET");
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(true);
        when(systemSwitchService.shouldRecordDetailedPageAction(any())).thenReturn(false);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldReturnNullForReadPermissionWhenRequestMethodIsNotGet() throws Exception {
        var handlerMethod = createHandlerMethod("requiresPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("POST");

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldMapKnownPermissionActionsToOperationActionTypes() throws Exception {
        assertThat(resolveActionType("requiresUpdatePermissionMethod", "PUT")).isEqualTo("编辑");
        assertThat(resolveActionType("requiresDeletePermissionMethod", "DELETE")).isEqualTo("删除");
        assertThat(resolveActionType("requiresAuditPermissionMethod", "POST")).isEqualTo("审核");
        assertThat(resolveActionType("requiresExportPermissionMethod", "POST")).isEqualTo("导出");
        assertThat(resolveActionType("requiresPrintPermissionMethod", "POST")).isEqualTo("打印");
        assertThat(resolveActionType("requiresEditAliasPermissionMethod", "PUT")).isEqualTo("编辑");
    }

    @Test
    void shouldNormalizeViewAliasForDetailedPageAction() throws Exception {
        var handlerMethod = createHandlerMethod("requiresViewAliasPermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("GET");
        when(request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE)).thenReturn(Map.of());
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(true);
        when(systemSwitchService.shouldRecordDetailedPageAction("QUERY")).thenReturn(true);

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNotNull();
        assertThat(result.actionType()).isEqualTo("查询");
    }

    @Test
    void shouldFallbackUnknownPermissionActionByRequestMethod() throws Exception {
        assertThat(resolveActionType("requiresUnknownPermissionMethod", "POST")).isEqualTo("新增");
        assertThat(resolveActionType("requiresUnknownPermissionMethod", "PUT")).isEqualTo("编辑");
        assertThat(resolveActionType("requiresUnknownPermissionMethod", "PATCH")).isEqualTo("编辑");
        assertThat(resolveActionType("requiresUnknownPermissionMethod", "DELETE")).isEqualTo("删除");
        assertThat(resolveActionType("requiresUnknownPermissionMethod", "GET")).isNull();
        assertThat(resolveActionType("requiresUnknownPermissionMethod", null)).isNull();
    }

    @Test
    void shouldReturnNull_whenRequiresPermissionResourceBlank() throws Exception {
        var handlerMethod = createHandlerMethod("blankResourcePermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("POST");

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldReturnNull_whenRequiresPermissionResourceDefaultBlank() throws Exception {
        var handlerMethod = createHandlerMethod("defaultBlankResourcePermissionMethod");
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn("POST");

        OperationLogMetadata result = resolver.resolveMetadata(handlerMethod, request);

        assertThat(result).isNull();
    }

    @Test
    void shouldDetectReadOnlyMethods() {
        assertThat(resolver.isReadOnlyMethod("GET")).isTrue();
        assertThat(resolver.isReadOnlyMethod("HEAD")).isTrue();
        assertThat(resolver.isReadOnlyMethod("OPTIONS")).isTrue();
        assertThat(resolver.isReadOnlyMethod("POST")).isFalse();
        assertThat(resolver.isReadOnlyMethod("PUT")).isFalse();
        assertThat(resolver.isReadOnlyMethod("DELETE")).isFalse();
    }

    @Test
    void shouldDetectPathVariableId() {
        var request = mock(HttpServletRequest.class);
        when(request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE)).thenReturn(Map.of("id", "123"));

        assertThat(resolver.hasPathVariableId(request)).isTrue();
    }

    @Test
    void shouldReturnFalse_whenNoPathVariable() {
        var request = mock(HttpServletRequest.class);
        request.setAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE, Map.of());

        assertThat(resolver.hasPathVariableId(request)).isFalse();
    }

    @Test
    void shouldReturnFalse_whenNoUriVariablesAttribute() {
        var request = mock(HttpServletRequest.class);

        assertThat(resolver.hasPathVariableId(request)).isFalse();
    }

    @Test
    void shouldReturnFalse_whenPathVariableIdBlank() {
        var request = mock(HttpServletRequest.class);
        when(request.getAttribute(HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE)).thenReturn(Map.of("id", "  "));

        assertThat(resolver.hasPathVariableId(request)).isFalse();
    }

    private String resolveActionType(String methodName, String httpMethod) throws Exception {
        var handlerMethod = createHandlerMethod(methodName);
        var request = mock(HttpServletRequest.class);
        when(request.getMethod()).thenReturn(httpMethod);
        when(systemSwitchService.shouldRecordDetailedPageActions()).thenReturn(false);
        when(systemSwitchService.shouldAutoRecordAllWriteOperations()).thenReturn(true);

        OperationLogMetadata metadata = resolver.resolveMetadata(handlerMethod, request);

        return metadata == null ? null : metadata.actionType();
    }

    private HandlerMethod createHandlerMethod(String methodName) throws Exception {
        Method method = TestController.class.getDeclaredMethod(methodName);
        return new HandlerMethod(new TestController(), method);
    }

    static class TestController {
        public void noAnnotationMethod() {}

        @OperationLoggable(moduleName = "测试模块", moduleNameField = "moduleKey", actionType = "新增", businessNoFields = {"id"})
        public void loggableMethod() {}

        @RequiresPermission(resource = "test", action = "read")
        public void requiresPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "read")
        public void requiresDepartmentReadPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "create")
        public void requiresCreatePermissionMethod() {}

        @RequiresPermission(resource = "department", action = "update")
        public void requiresUpdatePermissionMethod() {}

        @RequiresPermission(resource = "department", action = "delete")
        public void requiresDeletePermissionMethod() {}

        @RequiresPermission(resource = "department", action = "audit")
        public void requiresAuditPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "export")
        public void requiresExportPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "print")
        public void requiresPrintPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "view")
        public void requiresViewAliasPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "edit")
        public void requiresEditAliasPermissionMethod() {}

        @RequiresPermission(resource = "department", action = "unknown")
        public void requiresUnknownPermissionMethod() {}

        @RequiresPermission(resource = " ", action = "create")
        public void blankResourcePermissionMethod() {}

        @RequiresPermission
        public void defaultBlankResourcePermissionMethod() {}
    }
}
