package com.leo.erp.system.operationlog.support;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class OperationLogMetadataTest {

    @Test
    void shouldCreateRecord() {
        var metadata = new OperationLogMetadata(
                "测试模块", "新增", new String[]{"id", "orderNo"}, false
        );

        assertThat(metadata.moduleName()).isEqualTo("测试模块");
        assertThat(metadata.actionType()).isEqualTo("新增");
        assertThat(metadata.businessNoFields()).containsExactly("id", "orderNo");
        assertThat(metadata.autoGenerated()).isFalse();
    }

    @Test
    void shouldCreateWithEmptyFields() {
        var metadata = new OperationLogMetadata(
                "模块", "查询", new String[0], true
        );

        assertThat(metadata.moduleName()).isEqualTo("模块");
        assertThat(metadata.actionType()).isEqualTo("查询");
        assertThat(metadata.businessNoFields()).isEmpty();
        assertThat(metadata.autoGenerated()).isTrue();
    }
}
