package com.leo.erp.finance.payment.web.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public record PaymentResponse(
        Long id,
        String paymentNo,
        String businessType,
        String paymentPurpose,
        String counterpartyCode,
        String counterpartyName,
        Long sourceStatementId,
        Long sourcePurchaseOrderId,
        String purchaseOrderNo,
        String supplierCode,
        String supplierName,
        Long settlementCompanyId,
        String settlementCompanyName,
        LocalDate paymentDate,
        String payType,
        BigDecimal amount,
        String status,
        boolean deletedFlag,
        String operatorName,
        String remark,
        List<PaymentAllocationResponse> items
) {
    public PaymentResponse(Long id,
                           String paymentNo,
                           String businessType,
                           String counterpartyCode,
                           String counterpartyName,
                           Long sourceStatementId,
                           LocalDate paymentDate,
                           String payType,
                           BigDecimal amount,
                           String status,
                           boolean deletedFlag,
                           String operatorName,
                           String remark,
                           List<PaymentAllocationResponse> items) {
        this(
                id,
                paymentNo,
                businessType,
                null,
                counterpartyCode,
                counterpartyName,
                sourceStatementId,
                null,
                null,
                null,
                null,
                null,
                null,
                paymentDate,
                payType,
                amount,
                status,
                deletedFlag,
                operatorName,
                remark,
                items
        );
    }

    public PaymentResponse(Long id,
                           String paymentNo,
                           String businessType,
                           String counterpartyCode,
                           String counterpartyName,
                           Long sourceStatementId,
                           LocalDate paymentDate,
                           String payType,
                           BigDecimal amount,
                           String status,
                           String operatorName,
                           String remark,
                           List<PaymentAllocationResponse> items) {
        this(
                id,
                paymentNo,
                businessType,
                null,
                counterpartyCode,
                counterpartyName,
                sourceStatementId,
                null,
                null,
                null,
                null,
                null,
                null,
                paymentDate,
                payType,
                amount,
                status,
                false,
                operatorName,
                remark,
                items
        );
    }

    public PaymentResponse(Long id,
                           String paymentNo,
                           String businessType,
                           String counterpartyName,
                           Long sourceStatementId,
                           LocalDate paymentDate,
                           String payType,
                           BigDecimal amount,
                           String status,
                           String operatorName,
                           String remark,
                           List<PaymentAllocationResponse> items) {
        this(
                id,
                paymentNo,
                businessType,
                null,
                null,
                counterpartyName,
                sourceStatementId,
                null,
                null,
                null,
                null,
                null,
                null,
                paymentDate,
                payType,
                amount,
                status,
                false,
                operatorName,
                remark,
                items
        );
    }
}
