DO $$
DECLARE
    placeholder_pdf_form text := '{"page":{"width":595,"height":842},"fields":{"placeholder":{"source":"placeholder","left":28,"top":28,"width":539,"height":24}},"static":[{"type":"text","text":"文件托管模板待同步","left":28,"top":28,"width":539,"height":24}]}';
BEGIN
    INSERT INTO sys_print_template (
        id,
        bill_type,
        template_name,
        template_code,
        template_html,
        is_default,
        created_by,
        created_name,
        created_at,
        updated_by,
        updated_name,
        updated_at,
        deleted_flag,
        template_type,
        engine,
        asset_ref,
        version_no,
        status,
        sync_mode,
        source_ref,
        source_checksum,
        settlement_company_id,
        settlement_company_name
    )
    VALUES
        (
            322775358715723776,
            'freight-bill',
            '物流配送单',
            'TPL_322775358715723776',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/freight-bill-delivery.layout.json',
            'd5293c5f41d37e64807ba3075c391e86494740e7ffa170ba746b1c220d5bf3b9',
            307698191887761408,
            '嘉兴颖捷建材有限公司'
        ),
        (
            700540000000000024,
            'freight-bill',
            '物流单A版',
            'TPL_700540000000000024',
            'LODOP.PRINT_INIT("文件托管模板待同步");',
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'COORD',
            'LODOP',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/freight-bill-a.lodop.txt',
            'e5fb4df4c9b6da2a37137127a5936e214ea4e08087e77df8dcd472af7288efa0',
            307698191887761408,
            '嘉兴颖捷建材有限公司'
        ),
        (
            700540000000000026,
            'freight-statement',
            '物流对账单-汇总',
            'TPL_700540000000000026',
            'LODOP.PRINT_INIT("文件托管模板待同步");',
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'COORD',
            'LODOP',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/freight-statement-summary.lodop.txt',
            '682cc5b7bf7cb69fd6456f3a5320411a9cdcba5a36efb59c5a89b1079712e7e7',
            307698191887761408,
            '嘉兴颖捷建材有限公司'
        ),
        (
            700540000000000028,
            'customer-statement',
            '客户对账单-A4',
            'TPL_700540000000000028',
            'LODOP.PRINT_INIT("文件托管模板待同步");',
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'COORD',
            'LODOP',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/customer-statement-a4.lodop.txt',
            '973eb762f621de0d40a1685cc36bf754a44c64dc937e10b8be7311e3e24c6470',
            307698191887761408,
            '嘉兴颖捷建材有限公司'
        ),
        (
            700540000000000029,
            'sales-order',
            '颖捷A4打印_带备注 PDF',
            'SALES_ORDER_YINGJIE_A4_REMARK_PDF',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/yingjie-a4-remark.layout.json',
            '50043ebddc0ac02fdb707f753b8649ccc09033929b31dde01ab8081bc8998616',
            307698191887761408,
            '嘉兴颖捷建材有限公司'
        )
    ON CONFLICT (id) DO UPDATE
    SET
        bill_type = EXCLUDED.bill_type,
        template_name = EXCLUDED.template_name,
        template_code = EXCLUDED.template_code,
        template_html = sys_print_template.template_html,
        is_default = EXCLUDED.is_default,
        updated_by = 0,
        updated_name = 'flyway',
        updated_at = CURRENT_TIMESTAMP,
        deleted_flag = EXCLUDED.deleted_flag,
        template_type = EXCLUDED.template_type,
        engine = EXCLUDED.engine,
        asset_ref = EXCLUDED.asset_ref,
        version_no = GREATEST(sys_print_template.version_no, EXCLUDED.version_no),
        status = EXCLUDED.status,
        sync_mode = EXCLUDED.sync_mode,
        source_ref = EXCLUDED.source_ref,
        source_checksum = EXCLUDED.source_checksum,
        settlement_company_id = EXCLUDED.settlement_company_id,
        settlement_company_name = EXCLUDED.settlement_company_name;
END
$$;
