DO $$
DECLARE
    placeholder_pdf_form text := '{"page":{"width":595,"height":842},"fields":{"placeholder":{"source":"placeholder","left":28,"top":28,"width":539,"height":24}},"static":[{"type":"text","text":"文件托管模板待同步","left":28,"top":28,"width":539,"height":24}]}';
BEGIN
    INSERT INTO sys_print_template (
        id,
        bill_type,
        template_name,
        template_code,
        template_html,
        is_default,
        created_by,
        created_name,
        created_at,
        updated_by,
        updated_name,
        updated_at,
        deleted_flag,
        template_type,
        engine,
        asset_ref,
        version_no,
        status,
        sync_mode,
        source_ref,
        source_checksum,
        settlement_company_id,
        settlement_company_name
    )
    VALUES
        (
            700540000000000030,
            'freight-bill',
            '默认物流单 PDF',
            'DEFAULT_LOGISTICS_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-logistics.layout.json',
            'b37dbdddac02b102ee8a94eb6a2661d4377a1cbdf700f8ec7f9f259b42ec9df7',
            NULL,
            NULL
        ),
        (
            700540000000000031,
            'purchase-order',
            '默认采购订单 PDF',
            'DEFAULT_PURCHASE_ORDER_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-purchase-order.layout.json',
            'eeafeed9a49bdb05186846318a038d4b6e03507e8ddd9de616140f6ca6034a4d',
            NULL,
            NULL
        ),
        (
            700540000000000032,
            'inventory-report',
            '默认报表 PDF',
            'DEFAULT_REPORT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-report.layout.json',
            'a644b9ad4a1126d3a44f5e731d77fb1924349b1c64f301ec6d69ebda136f217f',
            NULL,
            NULL
        ),
        (
            700540000000000033,
            'sales-order',
            '默认销售订单 PDF',
            'DEFAULT_SALES_ORDER_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-sales-order.layout.json',
            'b7f21ce4cf3c1c39ee2c9e27092fde399b182bdcee3430726a145f47e084e95c',
            NULL,
            NULL
        ),
        (
            700540000000000034,
            'customer-statement',
            '默认客户对账 PDF',
            'DEFAULT_CUSTOMER_STATEMENT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-customer-statement.layout.json',
            '58260040d67911a508ce896a60b42f9d741900f641021255bf95a33e0dfaefc9',
            NULL,
            NULL
        ),
        (
            700540000000000035,
            'purchase-inbound',
            '默认采购入库 PDF',
            'DEFAULT_PURCHASE_INBOUND_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-purchase-inbound.layout.json',
            '20880558832df0b189748c7b65cddc64b5002aa94795307fcf29e8b432f3e01f',
            NULL,
            NULL
        ),
        (
            700540000000000036,
            'purchase-contract',
            '默认采购合同 PDF',
            'DEFAULT_PURCHASE_CONTRACT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-purchase-contract.layout.json',
            'dba81e58f4ae8ed367c04b9315ab7c25e6ffd3d5ac97fa05b48d2bacb88d8825',
            NULL,
            NULL
        ),
        (
            700540000000000037,
            'sales-outbound',
            '默认销售出库 PDF',
            'DEFAULT_SALES_OUTBOUND_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-sales-outbound.layout.json',
            '53934fdc1b905eb32e430bf2909fcd96748d4e10f955967994f690370c512de4',
            NULL,
            NULL
        ),
        (
            700540000000000038,
            'sales-contract',
            '默认销售合同 PDF',
            'DEFAULT_SALES_CONTRACT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-sales-contract.layout.json',
            '0ab9eef4c73325e39c6969012e5e332718a8bb0fddf7c1ec0c8789bd7d7db3ff',
            NULL,
            NULL
        ),
        (
            700540000000000039,
            'supplier-statement',
            '默认供应商对账 PDF',
            'DEFAULT_SUPPLIER_STATEMENT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-supplier-statement.layout.json',
            'b29cdc5aef4a60bbe4b83ea99d6115767cc6136d53c7181b917d40f7c381927f',
            NULL,
            NULL
        ),
        (
            700540000000000040,
            'freight-statement',
            '默认物流对账 PDF',
            'DEFAULT_FREIGHT_STATEMENT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-freight-statement.layout.json',
            '136d40c638c51789ef9a1c9f11ecbb0006086993b69ae5035925761579df50b3',
            NULL,
            NULL
        )
    ON CONFLICT (id) DO UPDATE
    SET
        bill_type = EXCLUDED.bill_type,
        template_name = EXCLUDED.template_name,
        template_code = EXCLUDED.template_code,
        template_html = sys_print_template.template_html,
        is_default = EXCLUDED.is_default,
        updated_by = 0,
        updated_name = 'flyway',
        updated_at = CURRENT_TIMESTAMP,
        deleted_flag = EXCLUDED.deleted_flag,
        template_type = EXCLUDED.template_type,
        engine = EXCLUDED.engine,
        asset_ref = EXCLUDED.asset_ref,
        version_no = GREATEST(sys_print_template.version_no, EXCLUDED.version_no),
        status = EXCLUDED.status,
        sync_mode = EXCLUDED.sync_mode,
        source_ref = EXCLUDED.source_ref,
        source_checksum = EXCLUDED.source_checksum,
        settlement_company_id = EXCLUDED.settlement_company_id,
        settlement_company_name = EXCLUDED.settlement_company_name;
END
$$;
