DO $$
DECLARE
    placeholder_pdf_form text := '{"page":{"width":595,"height":842},"fields":{"placeholder":{"source":"placeholder","left":28,"top":28,"width":539,"height":24}},"static":[{"type":"text","text":"文件托管模板待同步","left":28,"top":28,"width":539,"height":24}]}';
BEGIN
    INSERT INTO sys_print_template (
        id,
        bill_type,
        template_name,
        template_code,
        template_html,
        is_default,
        created_by,
        created_name,
        created_at,
        updated_by,
        updated_name,
        updated_at,
        deleted_flag,
        template_type,
        engine,
        asset_ref,
        version_no,
        status,
        sync_mode,
        source_ref,
        source_checksum,
        settlement_company_id,
        settlement_company_name
    )
    VALUES
        (
            700540000000000030,
            'freight-bill',
            '默认物流 PDF',
            'DEFAULT_LOGISTICS_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-logistics.layout.json',
            'e4586f52f923ef0151446a3ca9bfbdac3ddc987fdce87425992fc62702d35b65',
            NULL,
            NULL
        ),
        (
            700540000000000031,
            'purchase-order',
            '默认采购 PDF',
            'DEFAULT_PURCHASE_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-purchase.layout.json',
            '9960719640e2a0fc20ae485365ae000f8010b9c92509f906db0dc38728ed05c1',
            NULL,
            NULL
        ),
        (
            700540000000000032,
            'inventory-report',
            '默认报表 PDF',
            'DEFAULT_REPORT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-report.layout.json',
            'a644b9ad4a1126d3a44f5e731d77fb1924349b1c64f301ec6d69ebda136f217f',
            NULL,
            NULL
        ),
        (
            700540000000000033,
            'sales-order',
            '默认销售 PDF',
            'DEFAULT_SALES_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-sales.layout.json',
            'e327d7b6fab2ca0b445e945c798f93ea04cb8e1d7c6faca668d35722349f0962',
            NULL,
            NULL
        ),
        (
            700540000000000034,
            'customer-statement',
            '默认对账 PDF',
            'DEFAULT_STATEMENT_PDF_FORM',
            placeholder_pdf_form,
            false,
            0,
            'system',
            CURRENT_TIMESTAMP,
            0,
            'flyway',
            CURRENT_TIMESTAMP,
            false,
            'PDF_FORM',
            'PDF_FORM',
            NULL,
            1,
            'ACTIVE',
            'FILE',
            'print-forms/default-statement.layout.json',
            '7beb49929a784b611dcd436f248c2a8e8eca3085dd5ff0bfefa16088a439648e',
            NULL,
            NULL
        )
    ON CONFLICT (id) DO UPDATE
    SET
        bill_type = EXCLUDED.bill_type,
        template_name = EXCLUDED.template_name,
        template_code = EXCLUDED.template_code,
        template_html = sys_print_template.template_html,
        is_default = EXCLUDED.is_default,
        updated_by = 0,
        updated_name = 'flyway',
        updated_at = CURRENT_TIMESTAMP,
        deleted_flag = EXCLUDED.deleted_flag,
        template_type = EXCLUDED.template_type,
        engine = EXCLUDED.engine,
        asset_ref = EXCLUDED.asset_ref,
        version_no = GREATEST(sys_print_template.version_no, EXCLUDED.version_no),
        status = EXCLUDED.status,
        sync_mode = EXCLUDED.sync_mode,
        source_ref = EXCLUDED.source_ref,
        source_checksum = EXCLUDED.source_checksum,
        settlement_company_id = EXCLUDED.settlement_company_id,
        settlement_company_name = EXCLUDED.settlement_company_name;
END
$$;
