package com.leo.erp.system.operationlog.support;

record OperationLogMetadata(
        String moduleName,
        String actionType,
        String[] businessNoFields,
        boolean autoGenerated
) {
}
