package com.leo.erp.system.operationlog.support;

record OperationLogMetadata(
        String moduleName,
        String moduleNameField,
        String actionType,
        String[] businessNoFields,
        String recordIdField,
        String moduleKeyField,
        boolean autoGenerated
) {
}
