package com.leo.erp.logistics.bill.web.dto;

import java.math.BigDecimal;

public record FreightBillItemResponse(
        Long id,
        Integer lineNo,
        String sourceNo,
        Long sourceSalesOutboundItemId,
        String sourceSalesOutboundStatus,
        Long settlementCompanyId,
        String settlementCompanyName,
        Long customerId,
        String customerName,
        Long projectId,
        String projectName,
        Long materialId,
        String materialCode,
        String materialName,
        String brand,
        String category,
        String material,
        String spec,
        String length,
        Integer quantity,
        String quantityUnit,
        BigDecimal pieceWeightTon,
        Integer piecesPerBundle,
        String batchNo,
        String batchNoNormalized,
        BigDecimal weightTon,
        Long warehouseId,
        String warehouseName,
        Long sourceFreightBillId,
        Long sourceFreightBillItemId,
        Long sourceSalesOrderItemId,
        String sourceSalesOrderStatus
) {
    public FreightBillItemResponse(Long id,
                                   Integer lineNo,
                                   String sourceNo,
                                   Long sourceSalesOutboundItemId,
                                   String sourceSalesOutboundStatus,
                                   Long settlementCompanyId,
                                   String settlementCompanyName,
                                   Long customerId,
                                   String customerName,
                                   Long projectId,
                                   String projectName,
                                   Long materialId,
                                   String materialCode,
                                   String materialName,
                                   String brand,
                                   String category,
                                   String material,
                                   String spec,
                                   String length,
                                   Integer quantity,
                                   String quantityUnit,
                                   BigDecimal pieceWeightTon,
                                   Integer piecesPerBundle,
                                   String batchNo,
                                   String batchNoNormalized,
                                   BigDecimal weightTon,
                                   Long warehouseId,
                                   String warehouseName,
                                   Long sourceFreightBillId,
                                   Long sourceFreightBillItemId) {
        this(id, lineNo, sourceNo, sourceSalesOutboundItemId, sourceSalesOutboundStatus, settlementCompanyId,
                settlementCompanyName, customerId, customerName, projectId, projectName, materialId, materialCode,
                materialName, brand, category, material, spec, length, quantity, quantityUnit, pieceWeightTon,
                piecesPerBundle, batchNo, batchNoNormalized, weightTon, warehouseId, warehouseName,
                sourceFreightBillId, sourceFreightBillItemId, null, null);
    }

    public FreightBillItemResponse(Long id,
                                   Integer lineNo,
                                   String sourceNo,
                                   Long sourceSalesOutboundItemId,
                                   String sourceSalesOutboundStatus,
                                   Long settlementCompanyId,
                                   String settlementCompanyName,
                                   Long customerId,
                                   String customerName,
                                   Long projectId,
                                   String projectName,
                                   Long materialId,
                                   String materialCode,
                                   String materialName,
                                   String brand,
                                   String category,
                                   String material,
                                   String spec,
                                   String length,
                                   Integer quantity,
                                   String quantityUnit,
                                   BigDecimal pieceWeightTon,
                                   Integer piecesPerBundle,
                                   String batchNo,
                                   String batchNoNormalized,
                                   BigDecimal weightTon,
                                   Long warehouseId,
                                   String warehouseName) {
        this(id, lineNo, sourceNo, sourceSalesOutboundItemId, sourceSalesOutboundStatus, settlementCompanyId,
                settlementCompanyName, customerId, customerName, projectId, projectName, materialId, materialCode,
                materialName, brand, category, material, spec, length, quantity, quantityUnit, pieceWeightTon,
                piecesPerBundle, batchNo, batchNoNormalized, weightTon, warehouseId, warehouseName, null, null);
    }

    public FreightBillItemResponse(Long id,
                                   Integer lineNo,
                                   String sourceNo,
                                   Long sourceSalesOutboundItemId,
                                   String sourceSalesOutboundStatus,
                                   Long settlementCompanyId,
                                   String settlementCompanyName,
                                   String customerName,
                                   String projectName,
                                   String materialCode,
                                   String materialName,
                                   String brand,
                                   String category,
                                   String material,
                                   String spec,
                                   String length,
                                   Integer quantity,
                                   String quantityUnit,
                                   BigDecimal pieceWeightTon,
                                   Integer piecesPerBundle,
                                   String batchNo,
                                   BigDecimal weightTon,
                                   String warehouseName) {
        this(id, lineNo, sourceNo, sourceSalesOutboundItemId, sourceSalesOutboundStatus, settlementCompanyId,
                settlementCompanyName, null, customerName, null, projectName, null, materialCode, materialName,
                brand, category, material, spec, length, quantity, quantityUnit, pieceWeightTon, piecesPerBundle,
                batchNo, null, weightTon, null, warehouseName, null, null);
    }

    public FreightBillItemResponse(Long id,
                                   Integer lineNo,
                                   String sourceNo,
                                   String customerName,
                                   String projectName,
                                   String materialCode,
                                   String materialName,
                                   String brand,
                                   String category,
                                   String material,
                                   String spec,
                                   String length,
                                   Integer quantity,
                                   String quantityUnit,
                                   BigDecimal pieceWeightTon,
                                   Integer piecesPerBundle,
                                   String batchNo,
                                   BigDecimal weightTon,
                                   String warehouseName) {
        this(id, lineNo, sourceNo, null, null, null, null, null, customerName, null, projectName, null,
                materialCode, materialName, brand, category, material, spec, length, quantity, quantityUnit,
                pieceWeightTon, piecesPerBundle, batchNo, null, weightTon, null, warehouseName, null, null);
    }
}
