package com.leo.erp.purchase.order.web.dto;

import java.math.BigDecimal;

public record PurchaseOrderItemResponse(
        Long id,
        Integer lineNo,
        Long materialId,
        String materialCode,
        String brand,
        String category,
        String material,
        String spec,
        String length,
        String unit,
        Long settlementCompanyId,
        String settlementCompanyName,
        Long warehouseId,
        String warehouseName,
        String batchNo,
        String batchNoNormalized,
        Integer remainingQuantity,
        Integer salesRemainingQuantity,
        BigDecimal salesRemainingWeightTon,
        Integer quantity,
        String quantityUnit,
        BigDecimal pieceWeightTon,
        Integer piecesPerBundle,
        BigDecimal weightTon,
        BigDecimal actualWeightTon,
        BigDecimal actualPieceWeightTon,
        BigDecimal lockedSalesWeightTon,
        BigDecimal unitPrice,
        BigDecimal amount
) {
    public PurchaseOrderItemResponse(Long id,
                                     Integer lineNo,
                                     String materialCode,
                                     String brand,
                                     String category,
                                     String material,
                                     String spec,
                                     String length,
                                     String unit,
                                     Long settlementCompanyId,
                                     String settlementCompanyName,
                                     String warehouseName,
                                     String batchNo,
                                     Integer remainingQuantity,
                                     Integer salesRemainingQuantity,
                                     BigDecimal salesRemainingWeightTon,
                                     Integer quantity,
                                     String quantityUnit,
                                     BigDecimal pieceWeightTon,
                                     Integer piecesPerBundle,
                                     BigDecimal weightTon,
                                     BigDecimal actualWeightTon,
                                     BigDecimal actualPieceWeightTon,
                                     BigDecimal lockedSalesWeightTon,
                                     BigDecimal unitPrice,
                                     BigDecimal amount) {
        this(id, lineNo, null, materialCode, brand, category, material, spec, length, unit,
                settlementCompanyId, settlementCompanyName, null, warehouseName, batchNo, null,
                remainingQuantity, salesRemainingQuantity, salesRemainingWeightTon, quantity, quantityUnit,
                pieceWeightTon, piecesPerBundle, weightTon, actualWeightTon, actualPieceWeightTon,
                lockedSalesWeightTon, unitPrice, amount);
    }

    public PurchaseOrderItemResponse(Long id,
                                     Integer lineNo,
                                     String materialCode,
                                     String brand,
                                     String category,
                                     String material,
                                     String spec,
                                     String length,
                                     String unit,
                                     String warehouseName,
                                     String batchNo,
                                     Integer remainingQuantity,
                                     Integer salesRemainingQuantity,
                                     BigDecimal salesRemainingWeightTon,
                                     Integer quantity,
                                     String quantityUnit,
                                     BigDecimal pieceWeightTon,
                                     Integer piecesPerBundle,
                                     BigDecimal weightTon,
                                     BigDecimal actualWeightTon,
                                     BigDecimal actualPieceWeightTon,
                                     BigDecimal unitPrice,
                                     BigDecimal amount) {
        this(id, lineNo, null, materialCode, brand, category, material, spec, length, unit,
                null, null, null, warehouseName, batchNo, null, remainingQuantity, salesRemainingQuantity,
                salesRemainingWeightTon, quantity, quantityUnit, pieceWeightTon, piecesPerBundle,
                weightTon, actualWeightTon, actualPieceWeightTon, BigDecimal.ZERO, unitPrice, amount);
    }
}
